-- +migrate Up
CREATE TABLE IF NOT EXISTS tests (
  id BIGINT NOT NULL AUTO_INCREMENT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);

-- +migrate Down
DROP TABLE IF EXISTS tests;